/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avatar-head.glb -o app/chat/avatar/_components/AvatarHead.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/avatar-head.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.Material_0} />
    </group>
  )
}

useGLTF.preload('/models/avatar-head.glb')
