export const TEXTURE_PATH = "/images/video-player.jpg";

export const CORRESPONDING_VISEME = {
  A: "mouthOpen",
  B: "mouthOpen",
  C: "mouthOpen",
  D: "mouthOpen",
  E: "mouthOpen",
  F: "mouthOpen",
  G: "mouthOpen",
  H: "mouthOpen",
  I: "mouthOpen",
  J: "mouthOpen",
  K: "mouthOpen",
  L: "mouthOpen",
  M: "mouthOpen",
  N: "mouthOpen",
  O: "mouthOpen",
  P: "mouthOpen",
  Q: "mouthOpen",
  R: "mouthOpen",
  S: "mouthOpen",
  T: "mouthOpen",
  U: "mouthOpen",
  V: "mouthOpen",
  W: "mouthOpen",
  X: "mouthOpen",
  Y: "mouthOpen",
  Z: "mouthOpen",
};
