export const CORRESPONDING_VISEME_CYB = {
  A: "jawOpen",
  B: "mouthClose",
  C: "jawOpen",
  D: "jawOpen",
  E: "jawOpen",
  F: "jawOpen",
  G: "jawOpen",
  H: "jawOpen",
  I: "jawOpen",
  J: "jawOpen",
  K: "jawOpen",
  L: "jawOpen",
  M: "mouthClose",
  N: "jawOpen",
  O: "jawOpen",
  P: "mouthClose", 
  Q: "jawOpen",
  R: "jawOpen",
  S: "jawOpen",
  T: "jawOpen",
  U: "jawOpen",
  V: "jawOpen",
  W: "jawOpen",
  X: "jawOpen",
  Y: "jawOpen",
  Z: "jawOpen",
};
